import type { Order, Product, Slide } from "./types";

export const nav = [
  { href: "/", label: "الرئيسية" },
  { href: "/shop", label: "المتجر" },
  { href: "/category/skin", label: "العناية بالبشرة" },
  { href: "/category/makeup", label: "المكياج" },
  { href: "/category/fragrance", label: "العطور" },
  { href: "/category/gifts", label: "مجموعات الهدايا" },
  { href: "/brands", label: "العلامات التجارية" },
];

export const slides: Slide[] = [
  {
    id: "spring",
    eyebrow: "تشكيلة الربيع",
    title: "جمال طبيعي يبرز أناقتك الحقيقية",
    text: "منتجات مختارة بعناية لبشرة أكثر إشراقًا وإطلالة تحكي قصتك",
    cta: "تسوقي الآن",
    href: "/shop",
    face: "/home/medad_home_assets/07_hero_woman_rose.png",
    products: "/home/medad_home_assets/08_hero_products.png",
    bg: "/home/medad_home_assets/07_hero_woman_rose.png",
  },
  {
    id: "care",
    eyebrow: "العناية اليومية",
    title: "عناية فاخرة تستحقها بشرتك",
    text: "سيروم وكريمات ومستحضرات تغذي بشرتك وتمنحها نعومة وإشراقًا يدومان",
    cta: "اكتشفي العناية",
    href: "/category/skin",
    face: "/images/hero-face-2.jpg",
    products: "/images/hero-prod-2.jpg",
    bg: "/images/hero-bg-2.jpg",
  },
  {
    id: "makeup",
    eyebrow: "ركن المكياج",
    title: "مكياج يبرز ملامحك بأناقة",
    text: "ألوان راقية وتغطية مخملية لإطلالة متكاملة من الصباح حتى المساء",
    cta: "تسوقي المكياج",
    href: "/category/makeup",
    face: "/images/hero-face-3.jpg",
    products: "/images/hero-prod-3.jpg",
    bg: "/images/hero-bg-3.jpg",
  },
  {
    id: "gifts",
    eyebrow: "موسم الهدايا",
    title: "هدايا تُغلّف بأناقة وتُهدى بحب",
    text: "مجموعات منسقة لمن تحبين، بتفاصيل فاخرة ولمسة خاصة من مداد",
    cta: "اكتشفي المجموعات",
    href: "/category/gifts",
    face: "/images/hero-face-4.jpg",
    products: "/images/hero-prod-4.jpg",
    bg: "/images/hero-bg-4.jpg",
  },
];

export const benefits: { id: string; image: string; title: string; text: string }[] = [
  { id: "welcome", image: "/benefits/welcome.png", title: "مرحبا سارة!", text: "لديك 1,250 نقطة" },
  { id: "points", image: "/benefits/points.png", title: "اكسب نقاط", text: "مع كل طلب" },
  { id: "birthday", image: "/benefits/birthday.png", title: "عروض خاصة", text: "في عيد ميلادك" },
  { id: "members", image: "/benefits/members.png", title: "مكافآت حصرية", text: "للأعضاء" },
];

export const categories: { id: string; label: string; href: string; image: string }[] = [
  { id: "skin", label: "العناية بالبشرة", href: "/category/skin", image: "/categories/skin.png" },
  { id: "makeup", label: "المكياج", href: "/category/makeup", image: "/categories/makeup.png" },
  { id: "fragrance", label: "العطور", href: "/category/fragrance", image: "/categories/fragrance.png" },
  { id: "hair", label: "العناية بالشعر", href: "/category/hair", image: "/categories/hair.png" },
  { id: "body", label: "العناية بالجسم", href: "/category/body", image: "/categories/body.png" },
  { id: "gifts", label: "مجموعات الهدايا", href: "/category/gifts", image: "/categories/gifts.png" },
  { id: "tools", label: "مستلزمات الجمال", href: "/category/tools", image: "/categories/tools.png" },
];

export const concerns = [
  { id: "sensitive", label: "البشرة الحساسة", photo: "/concerns/faces/sensitive.jpg", icon: "/concerns/icons/leaf.png" },
  { id: "hydrate", label: "ترطيب عميق", photo: "/concerns/faces/hydrate.jpg", icon: "/concerns/icons/drop.png" },
  { id: "bright", label: "تفتيح وتوحيد اللون", photo: "/concerns/faces/bright.jpg", icon: "/concerns/icons/sparkle.png" },
  { id: "acne", label: "حب الشباب", photo: "/concerns/faces/acne.jpg", icon: "/concerns/icons/dots.png" },
  { id: "aging", label: "مكافحة التجاعيد", photo: "/concerns/faces/aging.jpg", icon: "/concerns/icons/hourglass.png" },
];

const skinDesc =
  "تركيبة لطيفة مدروسة لبشرة أكثر نعومة وإشراقًا، بمستخلصات نباتية وقوام يذوب بسهولة على البشرة. استخدميه يوميًا صباحًا ومساءً على بشرة نظيفة.";

export const bestsellers: Product[] = [
  {
    id: "serum",
    name: "سيروم فيتامين سي لإشراقة البشرة",
    price: 18,
    rating: 4.9,
    reviews: 126,
    image: "/images/p-serum.jpg",
    category: "skin",
    brand: "Lancôme",
    brandSlug: "lancome",
    volume: "30 مل",
    kind: "serum",
    skinType: "البشرة الباهتة",
    desc: skinDesc,
  },
  {
    id: "cream",
    name: "كريم ترطيب وردي فاخر",
    price: 11.6,
    oldPrice: 14.5,
    rating: 4.8,
    reviews: 96,
    badge: "الأكثر مبيعًا",
    image: "/product/main.png",
    category: "skin",
    brand: "Medad",
    brandSlug: "medad",
    volume: "50 مل",
    kind: "cream",
    skinType: "البشرة الجافة",
    desc: skinDesc,
  },
  {
    id: "lipstick",
    name: "أحمر شفاه مطفي فاخر",
    price: 8,
    rating: 4.7,
    reviews: 74,
    image: "/images/p-lipstick.jpg",
    category: "makeup",
    brand: "Huda Beauty",
    brandSlug: "huda-beauty",
    volume: "3 غ",
    kind: "lipstick",
    desc: "لون مطفي مخملي بثبات طويل وراحة على الشفاه طوال اليوم.",
  },
  {
    id: "perfume",
    name: "عطر روز الفاخر للنساء",
    price: 42,
    rating: 4.9,
    reviews: 212,
    image: "/images/p-perfume.jpg",
    category: "fragrance",
    brand: "Dior",
    brandSlug: "dior",
    volume: "50 مل",
    kind: "perfume",
    desc: "عطر زهري دافئ يروي لحظة أنيقة، بثبات ناعم وأثر يبقى قريبًا من البشرة.",
  },
  {
    id: "cleanser",
    name: "غسول لطيف للبشرة الحساسة",
    price: 9.5,
    rating: 4.8,
    reviews: 98,
    image: "/images/p-cleanser.jpg",
    category: "skin",
    brand: "Clinique",
    brandSlug: "clinique",
    volume: "150 مل",
    kind: "cleanser",
    skinType: "البشرة الحساسة",
    desc: skinDesc,
  },
];

export const arrivals: Product[] = [
  {
    id: "oil",
    name: "زيت شعر مغذّي بالأرغان",
    price: 16,
    rating: 4.8,
    reviews: 64,
    image: "/images/p-oil.jpg",
    badge: "جديد",
    tone: "new",
    category: "hair",
    brand: "Olaplex",
    brandSlug: "olaplex",
    volume: "100 مل",
    kind: "oil",
    desc: "زيت خفيف يغذي الشعر ويقلل الهيشان ويمنح الأطراف لمعانًا صحيًا.",
  },
  {
    id: "set",
    name: "مجموعة العناية الكاملة للبشرة الجافة",
    price: 22,
    oldPrice: 28,
    rating: 4.9,
    reviews: 41,
    image: "/images/p-set.jpg",
    badge: "-20%",
    tone: "sale",
    category: "gifts",
    brand: "Medad",
    brandSlug: "medad",
    volume: "5 قطع",
    kind: "set",
    skinType: "البشرة الجافة",
    desc: "روتين متكامل للبشرة الجافة: غسول، تونر، سيروم، كريم، وقناع ليلي.",
  },
  {
    id: "eye",
    name: "كريم العناية حول العين",
    price: 16,
    rating: 4.6,
    reviews: 88,
    image: "/images/p-eye.jpg",
    category: "skin",
    brand: "Clinique",
    brandSlug: "clinique",
    volume: "15 مل",
    kind: "eye",
    skinType: "البشرة المختلطة",
    desc: skinDesc,
  },
  {
    id: "toner",
    name: "تونر ماء الورد الطبيعي",
    price: 9.5,
    rating: 4.7,
    reviews: 76,
    image: "/images/p-toner.jpg",
    badge: "جديد",
    tone: "new",
    category: "skin",
    brand: "Medad",
    brandSlug: "medad",
    volume: "200 مل",
    kind: "toner",
    skinType: "البشرة الحساسة",
    desc: skinDesc,
  },
  {
    id: "night",
    name: "مجموعة العناية الليلية لإشراقة فورية",
    price: 18,
    oldPrice: 22,
    rating: 4.8,
    reviews: 37,
    image: "/images/p-night.jpg",
    badge: "جديد",
    tone: "new",
    category: "skin",
    brand: "Medad",
    brandSlug: "medad",
    volume: "3 قطع",
    kind: "set",
    skinType: "البشرة الباهتة",
    desc: skinDesc,
  },
];

export const moreProducts: Product[] = [
  {
    id: "rose-cream",
    name: "كريم ترطيب وردي فاخر",
    price: 11.6,
    oldPrice: 14.5,
    rating: 4.8,
    reviews: 96,
    image: "/images/p-cream.jpg",
    badge: "-20%",
    tone: "sale",
    category: "skin",
    brand: "Medad",
    brandSlug: "medad",
    volume: "50 مل",
    kind: "cream",
    skinType: "البشرة الجافة",
    desc: "كريم ترطيب وردي فاخر بمستخلص الورد الطبيعي ومجموعة من المكونات المغذية التي تساعد على تحسين ملمس البشرة وتعزيز إشراقها. قوامه حريري يذوب على البشرة ويمنحها نعومة تدوم طوال اليوم.",
  },
  {
    id: "sunscreen",
    name: "واقي شمس خفيف الوزن SPF 50",
    price: 14.5,
    rating: 4.8,
    reviews: 112,
    image: "/images/p-cleanser.jpg",
    category: "skin",
    brand: "La Roche-Posay",
    brandSlug: "la-roche-posay",
    volume: "50 مل",
    kind: "sun",
    skinType: "البشرة الدهنية",
    desc: "حماية يومية خفيفة الملمس بعامل حماية 50، بلا أثر أبيض وبتغطية مريحة تحت المكياج.",
  },
  {
    id: "mask",
    name: "قناع الطين الوردي لتنقية البشرة",
    price: 11,
    rating: 4.7,
    reviews: 64,
    image: "/images/p-night.jpg",
    category: "skin",
    brand: "Medad",
    brandSlug: "medad",
    volume: "75 مل",
    kind: "mask",
    skinType: "البشرة الدهنية",
    desc: skinDesc,
  },
  {
    id: "hyaluronic",
    name: "سيروم حمض الهيالورونيك لترطيب عميق",
    price: 19,
    rating: 4.9,
    reviews: 91,
    image: "/images/p-serum.jpg",
    category: "skin",
    brand: "The Ordinary",
    brandSlug: "the-ordinary",
    volume: "30 مل",
    kind: "serum",
    skinType: "البشرة الجافة",
    desc: skinDesc,
  },
  {
    id: "palette",
    name: "باليت ظلال العيون الناعم",
    price: 22,
    oldPrice: 28,
    rating: 4.8,
    reviews: 58,
    image: "/images/hero-prod-3.jpg",
    badge: "-20%",
    tone: "sale",
    category: "makeup",
    brand: "Huda Beauty",
    brandSlug: "huda-beauty",
    volume: "12 لون",
    kind: "palette",
    desc: "درجات وردية وبنية قابلة للمزج لإطلالة نهارية أو مسائية.",
  },
  {
    id: "gloss",
    name: "ملمع شفاه لامع وردي",
    price: 12,
    rating: 4.6,
    reviews: 44,
    image: "/images/p-lipstick.jpg",
    category: "makeup",
    brand: "Huda Beauty",
    brandSlug: "huda-beauty",
    volume: "6 مل",
    kind: "lipstick",
    desc: "لمعة مريحة غير لزجة بلون وردي يبرز الشفاه.",
  },
  {
    id: "lavender",
    name: "عطر لافندر الفاخر",
    price: 12.5,
    rating: 4.8,
    reviews: 80,
    image: "/images/p-perfume.jpg",
    category: "fragrance",
    brand: "Medad",
    brandSlug: "medad",
    volume: "50 مل",
    kind: "perfume",
    desc: "عطر لافندر ناعم بلمسة بودرية أنثوية وثبات يومي مريح.",
  },
  {
    id: "body",
    name: "لوشن الجسم الوردي المخملي",
    price: 9.3,
    rating: 4.7,
    reviews: 55,
    image: "/images/p-cream.jpg",
    category: "body",
    brand: "Medad",
    brandSlug: "medad",
    volume: "250 مل",
    kind: "cream",
    desc: "لوشن خفيف للجسم برائحة الورد يترك البشرة ناعمة طوال اليوم.",
  },
  {
    id: "brush-set",
    name: "مجموعة فرش المكياج الوردية",
    price: 18,
    oldPrice: 24,
    rating: 4.6,
    reviews: 33,
    image: "/images/hero-prod-1.jpg",
    badge: "-25%",
    tone: "sale",
    category: "tools",
    brand: "Huda Beauty",
    brandSlug: "huda-beauty",
    volume: "8 قطع",
    kind: "set",
    desc: "فرش ناعمة لتوزيع الأساس والبودرة والظلال بدقة.",
  },
];

export const allProducts = [...bestsellers, ...arrivals, ...moreProducts];

export const articles = [
  {
    id: "ramadan",
    tag: "العناية",
    title: "روتين العناية بالبشرة في رمضان",
    image: "/images/article-1.jpg",
    excerpt:
      "في رمضان تتغير ساعات النوم والماء، فابدئي بغسول لطيف ثم سيروم خفيف، ورطّبي بكريم غني قبل السحور. وبعد الإفطار اكتفي بمنظف لطيف ومرطب وواقي شمس، وامنحي بشرتك ليلة هادئة بلا طبقات ثقيلة.",
  },
  {
    id: "foundation",
    tag: "المكياج",
    title: "دليل اختيار كريم الأساس المناسب لك",
    image: "/images/article-2.jpg",
    excerpt:
      "اختاري درجة الأساس في ضوء النهار، وجرّبيها على طرف الفك لا على راحة اليد. البشرة الجافة تفضّل قوامًا مرطبًا يذوب على الجلد، والبشرة الدهنية تفضّل قوامًا مطفيًا خفيفًا يثبت طوال اليوم.",
  },
  {
    id: "summer",
    tag: "البشرة",
    title: "أسرار البشرة المشرقة في فصل الصيف",
    image: "/images/article-3.jpg",
    excerpt:
      "الحرارة تكشف أي تقصير في الترطيب. استخدمي سيروم فيتامين سي صباحًا، وواقي شمس بعامل حماية 50، وقناعًا مهدئًا مرتين في الأسبوع. والماء البارد بعد التعرض للشمس يعيد للبشرة هدوءها.",
  },
];

export const brands = [
  { name: "LANCÔME", italic: false, slug: "lancome" },
  { name: "ESTÉE LAUDER", italic: false, slug: "estee-lauder" },
  { name: "CLINIQUE", italic: false, slug: "clinique" },
  { name: "SKINCEUTICALS", italic: false, slug: "skinceuticals" },
  { name: "The Ordinary", italic: true, slug: "the-ordinary" },
  { name: "NYX", italic: false, slug: "nyx" },
  { name: "HUDA BEAUTY", italic: false, slug: "huda-beauty" },
  { name: "CAUDALIE", italic: false, slug: "caudalie" },
];

export const categoryMeta: Record<string, { label: string; kicker: string; image: string }> = {
  skin: { label: "العناية بالبشرة", kicker: "بشرة أكثر إشراقًا .. كل يوم", image: "/images/hero-face-2.jpg" },
  makeup: { label: "المكياج", kicker: "ألوان ناعمة تبرز ملامحك", image: "/images/hero-face-3.jpg" },
  fragrance: { label: "العطور", kicker: "عطور تروي قصتك ..", image: "/images/hero-face-1.jpg" },
  hair: { label: "العناية بالشعر", kicker: "لمعة صحية من الجذور حتى الأطراف", image: "/images/hero-face-4.jpg" },
  body: { label: "العناية بالجسم", kicker: "نعومة تدوم طوال اليوم", image: "/images/face-2.jpg" },
  gifts: { label: "مجموعات الهدايا", kicker: "هدايا تُغلّف بأناقة وتُهدى بحب", image: "/images/gift.jpg" },
  tools: { label: "مستلزمات الجمال", kicker: "أدوات تكمّل طقوس جمالك", image: "/images/hero-prod-3.jpg" },
};

export const kindLabels: Record<string, string> = {
  cleanser: "منظفات الوجه",
  toner: "تونر",
  serum: "سيروم",
  cream: "مرطبات",
  eye: "العناية حول العين",
  sun: "واقي الشمس",
  mask: "مقشرات",
  lipstick: "الشفاه",
  palette: "العيون",
  perfume: "عطور",
  oil: "العناية بالشعر",
  set: "مجموعات",
};

export const skinTypes = ["البشرة الجافة", "البشرة الدهنية", "البشرة المختلطة", "البشرة الحساسة", "البشرة الباهتة"];

export const brandDirectory = [
  { slug: "lancome", name: "LANCÔME", group: "skin", featured: true, image: "/images/hero-prod-2.jpg", title: "أناقة فرنسية لكل بشرة", about: "لانكوم من أعرق بيوت الجمال، وتجمع بين العطور والعناية والمكياج بتركيبات فاخرة." },
  { slug: "estee-lauder", name: "ESTÉE LAUDER", group: "skin", featured: true, image: "/images/p-serum.jpg", title: "عناية مدروسة وإشراق يدوم", about: "إستي لودر تقدّم سيرومات وكريمات بمعايير مختبرات العناية المتقدمة." },
  { slug: "clinique", name: "CLINIQUE", group: "skin", featured: true, image: "/images/p-cleanser.jpg", title: "كلينيك", about: "مستحضرات عناية جلدية خالية من العطور المزعجة، مناسبة للبشرة الحساسة وتُختار حسب نوع البشرة." },
  { slug: "dior", name: "DIOR", group: "fragrance", featured: true, image: "/images/p-perfume.jpg", title: "فخامة العطر والإطلالة", about: "ديور يقدّم عطورًا ومكياجًا بحضور أنيق وتفاصيل تليق بالمناسبات والأيام العادية." },
  { slug: "huda-beauty", name: "HUDA BEAUTY", group: "makeup", featured: true, image: "/images/hero-face-3.jpg", title: "جمال بثقة .. لكل امرأة", about: "تأسست Huda Beauty على يد خبيرة التجميل هدى قطان، وأصبحت اليوم واحدة من أكثر العلامات التجارية تأثيرًا في عالم الجمال. تتميز بمنتجات عالية الأداء، تركيبات مبتكرة، وألوان مصممة لتناسب كل ألوان البشرة." },
  { slug: "the-ordinary", name: "The Ordinary", group: "skin", italic: true, image: "/images/p-serum.jpg", title: "مكونات فعالة بلا تعقيد", about: "تركيبات واضحة بمكوّن فعّال واحد، لمن تحب أن تعرف ماذا تضع على بشرتها." },
  { slug: "olaplex", name: "OLAPLEX", group: "hair", image: "/images/p-oil.jpg", title: "رابطة تحمي الشعر", about: "عناية ترمّم الروابط داخل الشعرة وتمنحها قوة ونعومة." },
  { slug: "la-roche-posay", name: "LA ROCHE-POSAY", group: "skin", image: "/images/p-cleanser.jpg", title: "عناية جلدية موثوقة", about: "مستحضرات بمياه لاروش بوزيه المعدنية، مخصصة للبشرة الحساسة." },
  { slug: "nyx", name: "NYX", group: "makeup", image: "/images/p-lipstick.jpg", title: "مكياج جريء وسهل", about: "ألوان واضحة وأسعار قريبة، لإطلالات يومية ومسائية." },
  { slug: "caudalie", name: "CAUDALIE", group: "skin", image: "/images/p-toner.jpg", title: "مستخلصات الكرمة", about: "عناية فرنسية بمستخلصات العنب والماء الحراري." },
  { slug: "skinceuticals", name: "SKINCEUTICALS", group: "skin", image: "/images/p-serum.jpg", title: "عناية بمستوى العيادات", about: "سيرومات مضادة للأكسدة بروتوكولات مدروسة." },
  { slug: "medad", name: "Medad", group: "skin", image: "/images/p-cream.jpg", title: "جمال مداد الهادئ", about: "تشكيلة مداد الخاصة: عناية ومكياج وعطور مختارة بعناية لمتجر واحد." },
  { slug: "chanel", name: "CHANEL", group: "fragrance", image: "/images/p-perfume.jpg", title: "الأيقونة التي لا تبهت", about: "عطور ومكياج بخطوط كلاسيكية وحضور واضح." },
  { slug: "mac", name: "MAC", group: "makeup", image: "/images/p-lipstick.jpg", title: "ألوان المحترفين", about: "مكياج بتغطية احترافية ودرجات تناسب كل البشرات." },
  { slug: "nars", name: "NARS", group: "makeup", image: "/images/hero-prod-3.jpg", title: "جرأة ناعمة", about: "بلاشر وأحمر شفاه بدرجات أصبحت مرجعًا في عالم الجمال." },
  { slug: "rare-beauty", name: "Rare Beauty", group: "makeup", image: "/images/hero-face-1.jpg", title: "جمال يشعر بالراحة", about: "مكياج سائل وخفيف مصمم ليتحرك مع البشرة." },
  { slug: "kiehls", name: "Kiehl's", group: "skin", image: "/images/p-cream.jpg", title: "تركيبات منذ الصيدلية", about: "كريمات وزيوت بعناية عملية ونتائج واضحة." },
];

export const sampleOrders: Order[] = [
  {
    id: "MD24893",
    date: "12 أغسطس 2024",
    time: "09:41 ص",
    status: "preparing",
    statusLabel: "قيد التجهيز",
    payment: "بطاقة بنكية",
    name: "سارة أحمد",
    phone: "+973 3999 1234",
    address: "المنامة، الدبلوماسية، البحرين",
    discount: 2,
    shipping: 0,
    items: [
      { id: "lavender", name: "عطر لافندر الفاخر", price: 12.5, qty: 1, image: "/images/p-perfume.jpg", volume: "50 مل" },
      { id: "set", name: "مجموعة العناية بالبشرة", price: 18, qty: 1, image: "/images/p-set.jpg", volume: "5 قطع" },
    ],
  },
  {
    id: "MD2485",
    date: "10 مايو 2024",
    time: "02:30 م",
    status: "delivered",
    statusLabel: "تم التسليم",
    payment: "Apple Pay",
    name: "سارة أحمد",
    phone: "+973 3999 1234",
    address: "المنامة، الدبلوماسية، البحرين",
    discount: 0,
    shipping: 0,
    items: [
      { id: "cream", name: "كريم الترطيب اليومي المشرق", price: 12.5, qty: 1, image: "/images/p-cream.jpg", volume: "50 مل" },
      { id: "serum", name: "سيروم فيتامين سي", price: 18, qty: 1, image: "/images/p-serum.jpg", volume: "30 مل" },
    ],
  },
  {
    id: "MD2401",
    date: "2 مايو 2024",
    time: "11:15 ص",
    status: "shipped",
    statusLabel: "تم الشحن",
    payment: "تمارا",
    name: "سارة أحمد",
    phone: "+973 3999 1234",
    address: "المنامة، الدبلوماسية، البحرين",
    discount: 0,
    shipping: 1.5,
    items: [{ id: "rose-cream", name: "كريم ترطيب وردي فاخر", price: 11.6, qty: 1, image: "/images/p-cream.jpg", volume: "50 مل" }],
  },
];
